files: ^backend/.+\.py
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black
        args: [--config=backend/pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.0
    hooks:
      - id: flake8
        name: flake8
        args: [ --config=backend/.flake8 ]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
