---
name: Checks

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python3 -m pip install 'poetry==1.1.13' 
          pip install -r requirements.dev.txt

      - name: Linting
        working-directory: ./backend
        run: |
          pre-commit run --all-files
